import pandas as pd

fortune = pd.read_csv("../fortune1000.csv", index_col = "Rank")
sectors = fortune.groupby("Sector")
print(fortune.head(3))
print(len(fortune))
print("----------------------------------------")
print(fortune.tail(3))
print("========================================")

print(sectors.get_group("Apparel")["Profits"].sum())
print("----------------------------------------")
print(sectors.max())
print(sectors.min())
print("----------------------------------------")
print(sectors.sum())
print("----------------------------------------")
print(sectors.mean())

print("========================================")
print(sectors["Revenue"].sum())
print("----------------------------------------")
print(sectors["Employees"].sum())
print(sectors["Profits"].max())
print("----------------------------------------")
print(sectors["Profits"].min())
print("----------------------------------------")
print(sectors["Employees"].mean())
print("----------------------------------------")
print(sectors[["Revenue", "Profits"]].sum())
